// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYOJ_DTTj458KLHkO8tmrRdUI9UhSCRXY',
    appId: '1:781589107048:web:2976a9d2f31f582f53c6dd',
    messagingSenderId: '781589107048',
    projectId: 'reloop-a35e9',
    authDomain: 'reloop-a35e9.firebaseapp.com',
    storageBucket: 'reloop-a35e9.firebasestorage.app',
    measurementId: 'G-6CSHJZ6JXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGVn1XQ8_WvjQVTtBG7jarrWXHTa6jCec',
    appId: '1:781589107048:android:6a1a7c63fe260cc153c6dd',
    messagingSenderId: '781589107048',
    projectId: 'reloop-a35e9',
    storageBucket: 'reloop-a35e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbJ3oI_RBx17RkyvFAYcigOb6hHh1X2Rg',
    appId: '1:781589107048:ios:971cc391337ed99e53c6dd',
    messagingSenderId: '781589107048',
    projectId: 'reloop-a35e9',
    storageBucket: 'reloop-a35e9.firebasestorage.app',
    iosBundleId: 'com.reloop.reloop',
  );
}
